services:
  postgres:
    container_name: dairectiv-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: dairectiv
      POSTGRES_PASSWORD: "0123456789"
      POSTGRES_DB: dairectiv
    ports:
      - "40010:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    container_name: dairectiv-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "40011:5672"
      - "40002:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  api:
    container_name: dairectiv-api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./api:/app
      - ./docker/api/Caddyfile:/app/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    environment:
      SERVER_NAME: :80, :443, localhost
      DATABASE_URL: postgresql://dairectiv:0123456789@postgres:5432/dairectiv?serverVersion=16&charset=utf8
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f/messages
    command: ["frankenphp", "run", "--config", "/app/Caddyfile"]
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq

  adminer:
    container_name: dairectiv-adminer
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "40003:8080"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: dairectiv-swagger
    ports:
      - "40004:8081"
    volumes:
      - ./oas/openapi.yaml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
      PORT: 8081

  app:
    container_name: dairectiv-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost
    depends_on:
      - api

volumes:
  postgres-data:
  caddy-data:
  caddy-config:
  rabbitmq-data:
