doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            chronos: Dairectiv\SharedKernel\Infrastructure\Doctrine\DBAL\Types\ChronosType
            object_value: Dairectiv\SharedKernel\Infrastructure\Doctrine\DBAL\Types\ObjectValueType
            authoring_directive_id: Dairectiv\Authoring\Infrastructure\Doctrine\DBAL\Types\DirectiveIdType
            authoring_workflow_example_id: Dairectiv\Authoring\Infrastructure\Doctrine\DBAL\Types\WorkflowExampleIdType
            authoring_workflow_step_id: Dairectiv\Authoring\Infrastructure\Doctrine\DBAL\Types\WorkflowStepIdType
            authoring_rule_example_id: Dairectiv\Authoring\Infrastructure\Doctrine\DBAL\Types\RuleExampleIdType

    orm:
        auto_mapping: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        mappings:
            Authoring:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Authoring/Domain'
                prefix: 'Dairectiv\Authoring\Domain'
                alias: Authoring
        controller_resolver:
            auto_mapping: false
        filters:
            soft_deleted_directive:
                class: Dairectiv\Authoring\Infrastructure\Doctrine\ORM\Filter\SoftDeletedDirectiveFilter
                enabled: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
