when@dev: &dev
    zenstruck_foundry:
        enable_auto_refresh_with_lazy_objects: true
        persistence:
            flush_once: true
        instantiator:
            use_constructor: false
when@test: *dev
