controllers:
    resource:
        path: ../src/Authoring/UserInterface/Http/Api
        namespace: Dairectiv\Authoring\UserInterface\Http\Api
    type: attribute
    name_prefix: api_authoring_
    prefix: /api/authoring
