parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Dairectiv\:
        resource: '../src/'
        exclude:
            - '../src/**/Domain/Object/**/*'
            - '../src/**/Application/**/{Input,Output}.php'
